include: package:flutter_lints/flutter.yaml

linter: 
  rules: 
    non_constant_identifier_names: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
    private_optional_parameter: false