name: imc_project_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.0.0
  supabase_flutter: ^1.10.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.6
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/login_image.svg
    - assets/images/splash.svg