name: Deploy to App Center
on:
  push:
    branches:
      - main

permissions: read-all

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  appcenter-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - run: flutter doctor -v

      - name: Checkout gallery code
        uses: actions/checkout@v3
      - run: |
          echo "{\"SUPABASE_URL\":\"${SUPABASE_URL}\", \"SUPABASE_ANON_KEY\":\"${SUPABASE_ANON_KEY}\"}" > env.json
          
          echo "Environment variables:"
          cat env.json
          
          echo "Building APK..."

          flutter pub get 
          flutter build apk --dart-define-from-file=env.json --no-tree-shake-icons

      - name: Deploy to AppCenter
        uses: avocaddo/AppCenter-Github-Action@v1.0.2
        with:
          token: ${{ secrets.APPCENTER_API_TOKEN }}
          command: appcenter distribute release -f build/app/outputs/flutter-apk/app-release.apk --group imc -a leninner/IMC-app