name: Deploy to App Center
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  appcenter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: master
          cache: flutter-master
      - run: flutter doctor -v

      - name: Checkout gallery code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: |
          flutter pub get 
          flutter build apk

      - name: Deploy to AppCenter
        uses: avocaddo/AppCenter-Github-Action@v1.0.2
        with:
          token: ${{ secrets.APPCENTER_API_TOKEN }}
          command: appcenter distribute release -f build/app/outputs/flutter-apk/app-release.apk --group imc -a leninner/IMC-app