name: Tests
on:
  pull_request:
    branches: [main, develop]

permissions: read-all

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: master
      - run: flutter doctor -v

      - name: Checkout gallery code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: flutter pub get

      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
      - name: Run Flutter unit tests
        run: flutter test
