name: IMC Flutter CI Testing
on:
  pull_request:
    branches: [main, develop]

permissions: read-all

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - run: flutter doctor -v

      - name: Checkout gallery code
        uses: actions/checkout@v3
      - run: |
          flutter pub get
          flutter analyze
      
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
      
      - name: Run Flutter unit tests
        run: flutter test
